### ISSUE TITLE
In Participant's Action history, "see more" and "see all" should work.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/streetcrm#298]
Vince was testing and said:

> ...in the participants tab. Action history shows the 5 most recent actions, but the "see more" or "see all" is just text, so is there no way to see participants' full action history?

**Comment by cecilia-donnelly** [comment]
I think there are two problems here:

1. The link wasn't styled as a link / wasn't obviously clickable (addressed in	c19e1df).
2. The "see more" text shows up as soon as a participant has attended 5 actions, so if they've attended exactly 5 then the "see more" text will appear but will have no effect.  It should show up once they've attended *6* actions, so that it is only visible if clicking it will actually do something.

**Comment by cecilia-donnelly** [comment]
Deployed on [2017-03-10].

**Comment by kfogel** [comment]
Vince followed up to say:

> Thank you for updating, I realize that was what I was running into with someone who had exactly 5 events. It looks great.
