### ISSUE TITLE
Advanced Search: add an "Any Leadership Level" choice in the leadership dropdown.

### ISSUE THREAD

**Issue by kfogel** [OpenTechStrategies/streetcrm#344]
From the 2019-02-04 meeting at SWOP with Jessica and Chris:

On the Advanced Search page, add a choice for "Any Leadership Level" -- that is, the union of all the existing leadership level options except for the first non-choice one (the "--------" line indicating no leadership level).

The "Any Leadership Level" wording is just to explain the meaning -- if we think of a more descriptive phrase, we can use that as the new dropdown choice instead.

**Comment by frankduncan** [comment]
Right now, it looks like the "--------" option is actually "Any Leadership Level" because it's returning all participants regardless of what I do with them with regard to leadership levels.  That matches how the code looks, so it looks like we can just change "-----" to be "Any Leadership Level" and this will be resolved.  But that leaves the open issue of there is no way to select for people who don't have any leadership level, so maybe that's a feature that we actually want?

**Comment by kfogel** [comment]
Yes, let's add a "No Leadership Level" option too, and change "--------" to "Any Leadership Level".

**Comment by frankduncan** [comment]
This uses the ModelChoiceField, which allows changing the empty_label, but doesn't allow arbitrary addition of items.  If we want to add "No Leadership Level", then that will take a bit of reworking on the form.  For now, we'll just fix the bug as it's stated.
